### ISSUE TITLE
About baseline methods for class-supervised disentanglement.

### ISSUE THREAD

**Issue by FreemanG** [avivga/lord-pytorch#2]
Hi. I am confused about the expression in you paper (Baseline, 4 EXPERIMENTS, page 6).

You climed the DrNet[1] as a class-supervised method. However, the DrNet does not use either class labes or content labels as your method did. The DrNet simply tries to differentiate clips of the same videos from clips of different videos, and the class labels are not needed. 

If I have missed something, please correct me. 

_[1] Emily L Denton and Vighnesh Birodkar. Unsupervised learning of disentangled representations
from video. In NIPS, 2017_

**Comment by avivga** [comment]
In DrNet, in order to differentiate clips you have to use the video labels explicitly to train a discriminator (video labels are essentially the class labels since there is only a single object in each video). Furthermore, their method borrows the class code from a different video frame of the same object, which is another explicit use of class supervision. We use the same level of supervision.

**Comment by FreemanG** [comment]
I think you do not need actual labels to differentiate video-i from video-j, the video index could do the job. 

And, do you mean that one object could have several different videos? I believe you can part one video (video-i) to several chunks of frames ([Xi,t], [Xi,t+k]) without knowing the label.

**Comment by avivga** [comment]
I believe I now understand your confusion. The fact that they assume videos are given, implies that you use _class supervision_ at the _frame level_. So for each object in the dataset, you are given a video, and you assume that all frames present only this specific object and therefore all the frames are images of a unique class. This is equivalent to get access to an image dataset with class label per image.

**Comment by FreemanG** [comment]
So I believe that you could call their method as class-supervised when "class" is corresponding to "content". As their title is "unsupervised learning", calling it as "class-supervised" is kind of puzzling.

Anyhow, your latent optimization method is quite impressive.
